CREATE TABLE [dbo].[ElectronicDevice]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[Nombre] VARCHAR(50) NOT NULL,
	[Marca] VARCHAR(50) NOT NULL,
	[Color] VARCHAR(50) NOT NULL,
	[Precio] DECIMAL NOT NULL,
	[Descripcion] VARCHAR(50) NOT NULL,
	CONSTRAINT [PK_ELECTRONIC] PRIMARY KEY CLUSTERED([Id]ASC)
)
